### ISSUE TITLE
If I want to build my own database, may I look at the storage?

### ISSUE THREAD

**Issue by HK09x** [RajithAshok/ThePlantApp_v2.3#1]
If I want to build my own database, may I look at the storage?

**Comment by RajithAshok** [comment]
Sure, I'd be happy to help!

Designing a database for an e-commerce application can be complex, but there are some general principles you can follow to create a well-structured database. Here are a few steps to help you get started:

1. <b>Identify the entities:</b> Identify the main entities in your e-commerce application. These could include products, customers, orders, payments, and so on. Each of these entities will have its attributes that need to be stored in the database. For example, a product might have attributes like name, price, description, and image.

2. <b>Define the relationships:</b> Once you have identified the entities, you need to define the relationships between them. For example, an order will be associated with a customer and contain one or more products. This relationship needs to be modelled in the database.

3. <b>Normalize the data:</b> Normalization is the process of organizing data in a way that eliminates redundant data and minimizes data inconsistencies. One way to do this is to break down large tables into smaller ones linked together through relationships. This makes it easier to update and maintain the data.

4. <b>Use appropriate data types:</b> Choose appropriate data types for each attribute. For example, use numeric data types for price and quantity, and use text data types for descriptions.

5. <b>Implement database security:</b> It's important to implement proper security measures to protect the database from unauthorized access. This includes setting up access controls, user authentication, and encryption of sensitive data.

By following these steps, you can create a well-structured database for your e-commerce application that is efficient, secure, and easy to maintain.

**Comment by HK09x** [comment]
I want to know what it will be. as a guideline

**Comment by RajithAshok** [comment]
Since the purpose of my application was to sell plants, I first listed the various kinds of plants before compiling a list of every plant that fell under each category. 

Below are the Collections and their fields:

- <b>Category collection</b> - Name and Image URL.
- <b>Plants collection</b> - Name, Description, Price, Image URL and categoryReference. 
- <b>Users collection</b> - Name, Email, Address and Phone number.
